#ifndef __ENUM_H__
#define __ENUM_H__

enum eOBJ_TYPE
{
	OBJ_BACKGROUND,
	OBJ_BUILD,
	OBJ_RESOURCE,
	OBJ_MINIRESOURCE,
	OBJ_DEAD_EFFECT,
	OBJ_UNIT,
	OBJ_EFFECT,
	OBJ_FOG,
	OBJ_INTERPACE,
	OBJ_MOUSE,
	OBJ_END,
};

enum eRESOURCE_TYPE
{
	RESOURCE_MINERAL,
	RESOURCE_GAS,
};

enum eTEAM_TYPE
{
	TEAM_PLAYER,
	TEAM_ENEMY,
	TEAM_END,
};

enum eEFFECT_TYPE
{
	EFFECT_PROBE,
	EFFECT_PROBE_DEAD,
	EFFECT_DRAGOON_ATT,
	EFFECT_PHOTON_ATT,
	EFFECT_DRAGOON_ATT_EX,
	EFFECT_DRAGOON_DEAD,
	EFFECT_ARCHON_ATT,
	EFFECT_ARCHON_DEAD,
	EFFECT_OBSERVER_DEAD,
	EFFECT_SCOUT_ATT,
	EFFECT_SCOUT_ATT2,
	EFFECT_SCOUT_ATT_EX,
	EFFECT_SCOUT_DEAD,
	EFFECT_TEMPLAR_SHAD,
	EFFECT_STORM,
	EFFECT_DARKARCHON_FEEDBACK,
	EFFECT_DARKARCHON_MINDCONTROL,
	EFFECT_DARKARCHON_MAELSTORM,
	EFFECT_DARKARCHON_DEAD,
	EFFECT_REVER_SCARAB,
	ERRECT_CORSAIR_ATT,
	EFFECT_ARBITER_ATT,
	EFFECT_ARBITER_RECALL_START,
	EFFECT_ARBITER_RECALL_END,
	EFFECT_ARBITER_STASISFIELD,
	EFFECT_INTERCEPTOR_ATT,
	EFFECT_INTERCEPTOR_DEAD,
	EFFECT_CARRIER_DEAD,
	EFFECT_SCARAB_MOVE,
	EFFECT_SCARAB_DEAD,
	EFFECT_PING,
	EFFECT_BUILD_DEAD,
	EFFECT_BUILD_DEAD2,
};

enum eRENDER_TYPE
{
	RENDER_BACKGROUND,
	RENDER_GROUND,
	RENDER_GROUND_EFFECT,
	RENDER_AIR_UNIT,
	RENDER_AIR_EFFECT,
	RENDER_FOG,
	RENDER_INTERPACE,
	RENDER_MOUSE,
	RENDER_END,
};

enum eALPH_TYPE
{
	ALPH_NOMAL,
	ALPH_NOMAL_CLOOCKING,
	ALPH_CREATE_CLOOCKING,
	LOOK_ALPH_NOMAL_CLOOCKING,
	LOOK_ALPH_CREATE_CLOOCKING,
};

enum eSCENE_TYPE
{
	SCENE_INTRO,
	SCENE_LOGO,
	SCENE_MENU,
	SCENE_STAGE,
	SCENE_END,
};

enum eTEXTURE_TYPE
{
	TEX_SINGLE,
	TEX_MULTI,
	TEX_END,
};

enum eBUILD_TYPE
{
	BUILD_NEXUS,
	BUILD_PYLON,
	BUILD_ASSIMILATOR,
	BUILD_GATEWAY,
	BUILD_FORGE,
	BUILD_PHOTON_CANNON,
	BUILD_CYBERNETICS_CORE,
	BUILD_SHIELD_BATTERY,
	BUILD_ROBOTICS_FACILITY,
	BUILD_STARGATE,
	BUILD_CITADEL_OF_ADUN,
	BUILD_ROBOTICS_SUPPORT_BAY,
	BUILD_FLEET_BEACON,
	BUILD_TEMPAR_ARCHIVES,
	BUILD_OBSERVATORY,
	BUILD_ARBITER_TRIBUNAL,
	BUILD_GROUND,
	BUILD_ARR,
	BUILD_END,
};

enum eBUILD_CREATE_TYPE
{
	BUILD_CREATE_NOMAL,
	BUILD_CREATE_CREATE,
	BUILD_CREATE_UNIT,
	BUILD_CREATE_UPGREADE,
	BUILD_CREATE_END,
};

enum eUNIT_TYPE
{
	UNIT_GROUND,
	UNIT_ARR,
	UNIT_END,
};

enum CHANNEL_TYPE
{
	CHANNEL_BGM,
	CHANNEL_MAIN,
	CHANNEL_EFFECT,
	CHANNEL_EFFECT2,
	CHANNEL_EFFECT3,
	CHANNEL_EFFECT_DEAD,
	CHANNEL_EFFECT_CREATE,
	CHANNEL_EFFECT_ATT,
	CHANNEL_EFFECT_ATT2,
	CHANNEL_EFFECT_ATT3,
	CHANNEL_EFFECT_ATT4,
	CHANNEL_UI,
	CHANNEL_END,
};

enum eUPGRADE_TYPE
{
	UPGRADE_GROUND_ATT,
	UPGRADE_GROUND_ARMOR,
	UPGRADE_AIR_ATT,
	UPGRADE_AIR_ARMOR,
	UPGRADE_SHILD,
	UPGRADE_DRAGOON_RANGE,
	UPGRADE_ZEALOT_SPEED,
	UPGRADE_HIGHTEMPLAR_STORM,
	UPGRADE_HIGHTEMPLAR_ILLUSION,
	UPGRADE_HIGHTEMPLAR_MPMAX,
	UPGRADE_DARKARCHON_MINDCONTRAL,
	UPGRADE_DARKARCHON_CONFUSION,
	UPGRADE_DARKARCHON_MPMAX,
	UPGRADE_SUTTLE_SPEED,
	UPGRADE_REAVER_DAMAGE,
	UPGRADE_REVER_COUNT,
	UPGRADE_OBSERVER_VIEW,
	UPGRADE_OBSERVER_SPEED,
	UPGRADE_SCOUT_RANGE,
	UPGRADE_SCOUT_SPEED,
	UPGRADE_CARRIER_INTERCETOR,
	UPGRADE_CORSAIR_WAP,
	UPGRADE_CORSAIR_MPMAX,
	UPGRADE_ARBITER_RECOLL,
	UPGRADE_ARBITER_STACISFIELD,
	UPGRADE_ARBITER_MPMAX,
	UPGRADE_END,
};

#endif